Repository Lovely-Development-Team/Elsewhen, pull requests merged in 2021-11, with the labels that each got.

#184 Added dismiss button to mac easter egg sheet
  Elsewhen/Views/EasterEggView.swift
Labels: macOS

#187 Comment out settings for App Icon release
  Elsewhen/Views/Settings.swift
Labels: iOS

#196 macOS: Time Code popover redesign (back to vertical)
  Elsewhen/Elements/Buttons/FormatStyleButton.swift
  Elsewhen/Elements/DateTimeSelection.swift
  Elsewhen/Elements/DateTimeZonePicker.swift
  MacElsewhen/Controllers/StatusBar/TimeCodesPopoverViewController.swift
Labels: enhancement, macOS

#197 Adjust datepicker button
  Elsewhen/Elements/DateTimeZonePicker.swift
Labels: enhancement, macOS
